# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 950a82b6d8da2202b3f8ad712c2cebe42c62b7e4c6c5730ff29ed4fd3283ff40352de49cdd0c64a41f5de558b2269dbb589eb8c5775c58844b916536f6464170

test:
  secret_key_base: b35fdc7cc79484ef94b217d991b20d54e3b6f378a64613685fce16815720f6b792edd157a60d29dfef2ed148169830943e255a32729bcc9015208a22e8fc5020

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
